project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hope-donoghue/ds334blog
      - icon: linkedin
        href: https://www.linkedin.com/in/hope-donoghue-2ba54b238/
format:
  html:
    theme: cerulean
    css: styles.css



